title: Prajwal Nagaraj
logo: /assets/img/headshot_circle.png
description: Business Analyst | Data Analyst | Post Grad @ SAIT | Quality Engineer @ Accenture | Driving Innovative Solutions, Enhancing Quality Processes
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
