title:   Prajwal Nagaraj
logo: /assets/img/Phead_circle.png
description: Business Analyst | Data Analyst | 
Post Grad @ SAIT | Quality Engineer @ Accenture | Driving Innovative Solutions, Enhancing Quality Processes
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
